general:
    random_state: 42
    device: "cuda:0"
    logdir: "../logs"

data:
    X_train: "../inputs/X_train.npy"
    y_train: "../inputs/y_train.npy"
    input_h: 137
    input_w: 236
    augmentation: [
        # "ShiftScaleRotate/shift_limit=0.075, scale_limit=0.1, rotate_limit=45, interpolation=1, border_mode=0, value=0, p=0.5"
    ]


model:
    input_dim: 1
    n_outputs: 186
    name: "resnet34"
    pretrained: !!python/bool False

training:
    loss: "CrossEntropyLoss"
    split: "KFold"
    n_splits: 5
    batch_size: 256
    epochs: 100
    n_worker: 8
    single_fold: !!python/bool False
    single_iter: !!python/bool False
    lr_scheduler:
        name: "CosineAnnealingLR"
        args: "T_max=20, eta_min=1e-4, last_epoch=-1"

optimizer:
    name: "SGD"
    args: "lr=1e-2, weight_decay=0., momentum=0.9, nesterov=True"
