general:
    random_state: 42
    device: "cuda:0"
    # logdir: "/content/drive/My\ Drive/Bengali.AI/logs"
    logdir: "../logs"

data:
    X_train: "../inputs/X_train.npy"
    y_train: "../inputs/y_train.npy"

model:
    input_dim: 1
    n_outputs: 186
    name: "resnet34"
    pretrained: !!python/bool False

training:
    loss: "CrossEntropyLoss"
    n_splits: 5
    batch_size: 256
    epochs: 30
    n_worker: 4
    single_fold: !!python/bool False
    single_iter: !!python/bool False

optimizer:
    name: "Adam"
    lr: !!python/float 1e-3
    weight_decay: !!python/float 5e-4
